services:
  bitcoin-fullnode-exporter:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: bitcoin-fullnode-prometheus-exporter
    restart: unless-stopped

    env_file:
      - .env

    environment:
      PROMETHEUS_HOST: 0.0.0.0

    ports:
      - "127.0.0.1:${PROMETHEUS_PORT:-9091}:${PROMETHEUS_PORT:-9091}"